export const UNAUTHORIZED = 'Unauthorized';
export const NOT_FOUND = 'NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const FORBIDDEN = 'FORBIDDEN';
export const EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN';
